project:
  type: website
  output-dir: docs
  render:
    - "index.qmd"
    - "about/*.qmd"
    - "en/index.qmd"
    - "en/glossary.qmd"
    - "en/study-design-*.qmd"
    - "en/frequentist-*.qmd"
    - "en/effects-*.qmd"
    - "jp/*.qmd"
    - "kanji_en/*.qmd"
    - "kanji_jp/*.qmd"
  resources:
    - from-coffee-chat-to-r/study-design.R
    - from-coffee-chat-to-r/frequentist.R
    - from-coffee-chat-to-r/effects.R
    - from-coffee-chat-to-r/logistic-regression.R
    - from-coffee-chat-to-r/ai-r.R
    - google232e7b0b40f73b28.html
    
website:
  title: "Coffee and Research"
  site-url: "https://gestimation.github.io/coffee-and-research/"
  google-analytics: "G-FCK3LX51C6"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "cifmodeling"
        href: https://gestimation.github.io/cifmodeling/
      - text: "airsetup"
        href: https://gestimation.github.io/airsetup/
      - text: "Giant Salamander Skillbox"
        href: https://github.com/gestimation/giant-salamander-skillbox
      - text: A Conversation (EN)
        menu:
          - text: Index
            href: en/index.qmd
          - text: Study design
            href: en/study-design-1.qmd
          - text: Frequentist Thinking
            href: en/frequentist-1.qmd
          - text: Frequentist Experiments
            href: en/frequentist-4.qmd
          - text: Effects and Time
            href: en/effects-1.qmd
      - text: A Conversation (JP)
        menu:
          - text: Index
            href: jp/index.qmd
          - text: Study Design
            href: jp/study-design-1.qmd
          - text: Frequentist Thinking
            href: jp/frequentist-1.qmd
          - text: Frequentist Experiments
            href: jp/frequentist-4.qmd
          - text: Effects and Time
            href: jp/effects-1.qmd
          - text: Regression
            href: jp/logistic-regression-1.qmd
          - text: Causal inference
            href: jp/causal-inference-1.qmd
          - text: Publishing a paper
            href: jp/publish-a-paper-1.qmd
      - text: 8 Elements (EN)
        href: kanji_en/index.qmd
      - text: 8 Elements (JP)
        href: kanji_jp/index.qmd

format:
  html:
    theme: cosmo
    toc: true
    css: styles.css
    page-layout: full
    canonical-url: true
    encoding: "utf-8"
    include-in-header:
      - includes/head.html
